horny:
  host: 127.0.0.1
  port: 6669
  base_domain: https://example.com
  admin_username: admin
  admin_password: your_secure_password
  default_resolution: MEDIUM # LOW MEDIUM OR HIGH
  share_id_length: 8
stash:
  server_ip: 127.0.0.1
  port: 5588
  api_key: yourStashAPIKeyGoesHere
disclaimer: "This content is shared for private use only. Unauthorized distribution is prohibited. This site does not encourage/condone illegal sexual conduct and is intended solely to provide visual pleasure for ADULTS only. Please leave this site if you are under 18 or if you find mature/explicit content offensive. All mature/explicit content on this site is strictly in compliance with 18 U.S.C. ยง Code 2257 i.e. all performers featured are 18 years or older of age. This site and all its associated domains being in accordance with 17 U.S.C. ยง 512 and the Digital Millennium Copyright Act, responds to infringement notices within 24 hours."

